name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install OpenCV
      run: sudo apt-get install -y libopencv-dev

    - name: Install clang
      run: sudo apt-get install clang-11 libc++-11-dev libc++abi-11-dev clang-tools clang-tidy clang-format

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: |
        scan-build \
          --use-cc=clang \
          --use-c++=clang++ \
          --force-analyze-debug-code \
          -enable-checker alpha.clone \
          -enable-checker alpha.core \
          -enable-checker alpha.cplusplus \
          -enable-checker alpha.deadcode \
          -enable-checker alpha.llvm \
          -enable-checker alpha.security \
          -enable-checker alpha.security.cert \
          -enable-checker alpha.security.cert.pos \
          -enable-checker alpha.unix \
          -enable-checker core \
          -enable-checker cplusplus \
          -enable-checker debug \
          -enable-checker optin \
          -enable-checker security \
          -enable-checker unix \
          -v -v -v cmake \
          -DCMAKE_CXX_CLANG_TIDY="clang-tidy" \
          -DCMAKE_BUILD_TYPE=Debug \
          -DCMAKE_CXX_FLAGS="-pedantic -Wall -Wextra -Wshadow -Weffc++ -Wconversion -Werror" \
          -B ${{github.workspace}}/build

    - name: Build
      # Build your program with the given configuration
      run: |
        scan-build \
          --use-cc=clang \
          --use-c++=clang++ \
          --force-analyze-debug-code \
          -enable-checker alpha.clone \
          -enable-checker alpha.core \
          -enable-checker alpha.cplusplus \
          -enable-checker alpha.deadcode \
          -enable-checker alpha.llvm \
          -enable-checker alpha.security \
          -enable-checker alpha.security.cert \
          -enable-checker alpha.security.cert.pos \
          -enable-checker alpha.unix \
          -enable-checker core \
          -enable-checker cplusplus \
          -enable-checker debug \
          -enable-checker optin \
          -enable-checker security \
          -enable-checker unix \
          -v -v -v \
          cmake --build ${{github.workspace}}/build
