name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  static-analysis:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install OpenCV
      run: sudo apt-get install -y libopencv-dev

    - name: Install clang
      run: sudo apt-get install clang-11 libc++-11-dev libc++abi-11-dev clang-tools clang-tidy clang-format

    - name: Configure CMake
      run: |
        scan-build \
          --use-cc=clang \
          --use-c++=clang++ \
          --force-analyze-debug-code \
          -enable-checker alpha.clone \
          -enable-checker alpha.core \
          -enable-checker alpha.cplusplus \
          -enable-checker alpha.deadcode \
          -enable-checker alpha.llvm \
          -enable-checker alpha.security \
          -enable-checker alpha.security.cert \
          -enable-checker alpha.security.cert.pos \
          -enable-checker alpha.unix \
          -enable-checker core \
          -enable-checker cplusplus \
          -enable-checker debug \
          -enable-checker optin \
          -enable-checker security \
          -enable-checker unix \
          -v -v -v\
          cmake \
          -DCMAKE_CXX_CLANG_TIDY="clang-tidy" \
          -DCMAKE_BUILD_TYPE=Debug \
          -DCMAKE_CXX_FLAGS="-pedantic -Wall -Wextra -Wshadow -Weffc++ -Wconversion -Werror" \
          -B ${{github.workspace}}/build

    - name: Build
      # Build your program with the given configuration
      run: |
        scan-build \
          --use-cc=clang \
          --use-c++=clang++ \
          --force-analyze-debug-code \
          -enable-checker alpha.clone \
          -enable-checker alpha.core \
          -enable-checker alpha.cplusplus \
          -enable-checker alpha.deadcode \
          -enable-checker alpha.llvm \
          -enable-checker alpha.security \
          -enable-checker alpha.security.cert \
          -enable-checker alpha.security.cert.pos \
          -enable-checker alpha.unix \
          -enable-checker core \
          -enable-checker cplusplus \
          -enable-checker debug \
          -enable-checker optin \
          -enable-checker security \
          -enable-checker unix \
          -v -v -v \
          cmake --build ${{github.workspace}}/build

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install OpenCV
      run: sudo apt-get install -y libopencv-dev

    - name: Install gcc
      run: sudo apt-get install g++-11

    - name: Configure CMake
      run: |
          cmake \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_CXX_COMPILER="g++-11" \
          -DCMAKE_CXX_FLAGS="-ansi -pedantic -Wall -Wextra -Wshadow -Weffc++ -Wconversion -Werror" \
          -B ${{github.workspace}}/build

    - name: Build
      run: |
          cmake --build ${{github.workspace}}/build
